### ISSUE TITLE
SOA deployment Issue

### ISSUE THREAD

**Issue by sikendermd** [xebialabs-community/xld-oracle-soa-plugin#5]
Hi,
I am trying to deploy soa.CompositeSOAdeployable Spec(Application) with Discover-wls.domain Infrasturcture while the environment is udm.environment which is the soaprod01_cluster. 

The Error I can see is AttributeError: 'NoneType' object has no attribute 'address'
Please go through the log;  Can you tell me what may be the exact issue is;

<flashrichtext version="1">
  <textformat font="MuseoSans" size="12" color="0" bold="false" italic="false" underline="false" url="" target="" align="left" leftMargin="0" rightMargin="0" indent="0" leading="2" blockIndent="0" kerning="false" letterSpacing="0" display="block">(Starting the daemon on [Infrastructure/SOA/STX02VSOA11])</textformat>
  <textformat font="MuseoSans" size="12" color="734012" bold="false" italic="false" underline="false" url="" target="" align="left" leftMargin="0" rightMargin="0" indent="0" leading="2" blockIndent="0" kerning="false" letterSpacing="0" display="block">(
)</textformat>
  <textformat font="MuseoSans" size="12" color="0" bold="false" italic="false" underline="false" url="" target="" align="left" leftMargin="0" rightMargin="0" indent="0" leading="2" blockIndent="0" kerning="false" letterSpacing="0" display="block">(CLASSPATH=:/u01/app/oracle/product/fmw/oracle_common/soa/modules/oracle.soa.mgmt_11.1.1/soa-infra-mgmt.jar:/u01/app/oracle/product/fmw/oracle_common/soa/modules/commons-cli-1.1.jar:/u01/app/oracle/product/fmw/Oracle_SOA1/soa/modules/oracle.soa.fabric_11.1.1/fabric-runtime.jar:/u01/app/oracle/product/fmw/Oracle_SOA1/soa/modules/oracle.soa.fabric_11.1.1/soa-infra-tools.jar:/u01/app/oracle/product/fmw/Oracle_SOA1/soa/modules/oracle.soa.workflow_11.1.1/bpm-services.jar:/u01/app/oracle/product/fmw/Oracle_SOA1/soa/modules/oracle.soa.fabric_11.1.1/testfwk-xbeans.jar:/u01/app/oracle/product/fmw/Oracle_SOA1/soa/modules/oracle.soa.fabric_11.1.1/oracle-soa-client-api.jar:/u01/app/oracle/product/fmw/Oracle_SOA1/soa/modules/oracle.bpm.admin.lifecycle.jar:/u01/app/oracle/product/fmw/oracle_common/modules/oracle.classloader_11.1.1.jar:/u01/app/oracle/product/fmw/oracle_common/modules/org.apache.commons.logging_1.0.4.jar:/u01/app/oracle/product/fmw/oracle_common/modules/org.apache.commons.beanutils_1.6.jar:/u01/app/oracle/product/fmw/oracle_common/modules/oracle.ucp_11.1.0.jar:/u01/app/oracle/product/fmw/Oracle_SOA1/soa/modules/oracle.rules_11.1.1/rulesdk2.jar:/u01/app/oracle/product/fmw/Oracle_SOA1/soa/modules/oracle.rules_11.1.1/rl.jar:/u01/app/oracle/product/fmw/oracle_common/modules/oracle.adf.model_11.1.1/adfm.jar:/u01/app/oracle/product/fmw/oracle_common/modules/oracle.jdbc_11.1.1/ojdbc6dms.jar:/u01/app/oracle/product/fmw/oracle_common/modules/oracle.xdk_11.1.0/xmlparserv2.jar:/u01/app/oracle/product/fmw/Oracle_SOA1/communications/modules/usermessaging-command_11.1.1.jar)</textformat>
  <textformat font="MuseoSans" size="12" color="734012" bold="false" italic="false" underline="false" url="" target="" align="left" leftMargin="0" rightMargin="0" indent="0" leading="2" blockIndent="0" kerning="false" letterSpacing="0" display="block">(
)</textformat>
  <textformat font="MuseoSans" size="12" color="0" bold="false" italic="false" underline="false" url="" target="" align="left" leftMargin="0" rightMargin="0" indent="0" leading="2" blockIndent="0" kerning="false" letterSpacing="0" display="block">(CLASSPATH=:/u01/app/oracle/product/fmw/oracle_common/soa/modules/oracle.soa.mgmt_11.1.1/soa-infra-mgmt.jar:/u01/app/oracle/product/fmw/oracle_common/soa/modules/commons-cli-1.1.jar:/u01/app/oracle/product/fmw/Oracle_SOA1/soa/modules/oracle.soa.fabric_11.1.1/fabric-runtime.jar:/u01/app/oracle/product/fmw/Oracle_SOA1/soa/modules/oracle.soa.fabric_11.1.1/soa-infra-tools.jar:/u01/app/oracle/product/fmw/Oracle_SOA1/soa/modules/oracle.soa.workflow_11.1.1/bpm-services.jar:/u01/app/oracle/product/fmw/Oracle_SOA1/soa/modules/oracle.soa.fabric_11.1.1/testfwk-xbeans.jar:/u01/app/oracle/product/fmw/Oracle_SOA1/soa/modules/oracle.soa.fabric_11.1.1/oracle-soa-client-api.jar:/u01/app/oracle/product/fmw/Oracle_SOA1/soa/modules/oracle.bpm.admin.lifecycle.jar:/u01/app/oracle/product/fmw/oracle_common/modules/oracle.classloader_11.1.1.jar:/u01/app/oracle/product/fmw/oracle_common/modules/org.apache.commons.logging_1.0.4.jar:/u01/app/oracle/product/fmw/oracle_common/modules/org.apache.commons.beanutils_1.6.jar:/u01/app/oracle/product/fmw/oracle_common/modules/oracle.ucp_11.1.0.jar:/u01/app/oracle/product/fmw/Oracle_SOA1/soa/modules/oracle.rules_11.1.1/rulesdk2.jar:/u01/app/oracle/product/fmw/Oracle_SOA1/soa/modules/oracle.rules_11.1.1/rl.jar:/u01/app/oracle/product/fmw/oracle_common/modules/oracle.adf.model_11.1.1/adfm.jar:/u01/app/oracle/product/fmw/oracle_common/modules/oracle.jdbc_11.1.1/ojdbc6dms.jar:/u01/app/oracle/product/fmw/oracle_common/modules/oracle.xdk_11.1.0/xmlparserv2.jar:/u01/app/oracle/product/fmw/Oracle_SOA1/communications/modules/usermessaging-command_11.1.1.jar)</textformat>
  <textformat font="MuseoSans" size="12" color="734012" bold="false" italic="false" underline="false" url="" target="" align="left" leftMargin="0" rightMargin="0" indent="0" leading="2" blockIndent="0" kerning="false" letterSpacing="0" display="block">(
)</textformat>
  <textformat font="MuseoSans" size="12" color="0" bold="false" italic="false" underline="false" url="" target="" align="left" leftMargin="0" rightMargin="0" indent="0" leading="2" blockIndent="0" kerning="false" letterSpacing="0" display="block">(
CLASSPATH=/u01/app/oracle/product/fmw/patch_wls1036/profiles/default/sys_manifest_classpath/weblogic_patch.jar:/u01/app/oracle/product/fmw/patch_ocp371/profiles/default/sys_manifest_classpath/weblogic_patch.jar:/u01/app/oracle/product/fmw/jdk1.7.0_25/lib/tools.jar:/u01/app/oracle/product/fmw/wlserver_10.3/server/lib/weblogic_sp.jar:/u01/app/oracle/product/fmw/wlserver_10.3/server/lib/weblogic.jar:/u01/app/oracle/product/fmw/modules/features/weblogic.server.modules_10.3.6.0.jar:/u01/app/oracle/product/fmw/wlserver_10.3/server/lib/webservices.jar:/u01/app/oracle/product/fmw/modules/org.apache.ant_1.7.1/lib/ant-all.jar:/u01/app/oracle/product/fmw/modules/net.sf.antcontrib_1.1.0.0_1-0b2/lib/ant-contrib.jar::/u01/app/oracle/product/fmw/oracle_common/soa/modules/oracle.soa.mgmt_11.1.1/soa-infra-mgmt.jar:/u01/app/oracle/product/fmw/oracle_common/soa/modules/commons-cli-1.1.jar:/u01/app/oracle/product/fmw/Oracle_SOA1/soa/modules/oracle.soa.fabric_11.1.1/fabric-runtime.jar:/u01/app/oracle/product/fmw/Oracle_SOA1/soa/modules/oracle.soa.fabric_11.1.1/soa-infra-tools.jar:/u01/app/oracle/product/fmw/Oracle_SOA1/soa/modules/oracle.soa.workflow_11.1.1/bpm-services.jar:/u01/app/oracle/product/fmw/Oracle_SOA1/soa/modules/oracle.soa.fabric_11.1.1/testfwk-xbeans.jar:/u01/app/oracle/product/fmw/Oracle_SOA1/soa/modules/oracle.soa.fabric_11.1.1/oracle-soa-client-api.jar:/u01/app/oracle/product/fmw/Oracle_SOA1/soa/modules/oracle.bpm.admin.lifecycle.jar:/u01/app/oracle/product/fmw/oracle_common/modules/oracle.classloader_11.1.1.jar:/u01/app/oracle/product/fmw/oracle_common/modules/org.apache.commons.logging_1.0.4.jar:/u01/app/oracle/product/fmw/oracle_common/modules/org.apache.commons.beanutils_1.6.jar:/u01/app/oracle/product/fmw/oracle_common/modules/oracle.ucp_11.1.0.jar:/u01/app/oracle/product/fmw/Oracle_SOA1/soa/modules/oracle.rules_11.1.1/rulesdk2.jar:/u01/app/oracle/product/fmw/Oracle_SOA1/soa/modules/oracle.rules_11.1.1/rl.jar:/u01/app/oracle/product/fmw/oracle_common/modules/oracle.adf.model_11.1.1/adfm.jar:/u01/app/oracle/product/fmw/oracle_common/modules/oracle.jdbc_11.1.1/ojdbc6dms.jar:/u01/app/oracle/product/fmw/oracle_common/modules/oracle.xdk_11.1.0/xmlparserv2.jar:/u01/app/oracle/product/fmw/Oracle_SOA1/communications/modules/usermessaging-command_11.1.1.jar:/u01/app/oracle/product/fmw/Oracle_SOA1/common/wlst/lib/webcenter-admin-commands.jar:/u01/app/oracle/product/fmw/oracle_common/modules/oracle.jrf_11.1.1/jrf-wlstman.jar:/u01/app/oracle/product/fmw/oracle_common/common/wlst/lib/adf-share-mbeans-wlst.jar:/u01/app/oracle/product/fmw/oracle_common/common/wlst/lib/adfscripting.jar:/u01/app/oracle/product/fmw/oracle_common/common/wlst/lib/mdswlst.jar:/u01/app/oracle/product/fmw/oracle_common/common/wlst/resources/auditwlst.jar:/u01/app/oracle/product/fmw/oracle_common/common/wlst/resources/igfwlsthelp.jar:/u01/app/oracle/product/fmw/oracle_common/common/wlst/resources/jps-wlst.jar:/u01/app/oracle/product/fmw/oracle_common/common/wlst/resources/jrf-wlst.jar:/u01/app/oracle/product/fmw/oracle_common/common/wlst/resources/oamAuthnProvider.jar:/u01/app/oracle/product/fmw/oracle_common/common/wlst/resources/oamap_help.jar:/u01/app/oracle/product/fmw/oracle_common/common/wlst/resources/ossoiap.jar:/u01/app/oracle/product/fmw/oracle_common/common/wlst/resources/ossoiap_help.jar:/u01/app/oracle/product/fmw/oracle_common/common/wlst/resources/ovdwlsthelp.jar:/u01/app/oracle/product/fmw/oracle_common/common/wlst/resources/sslconfigwlst.jar:/u01/app/oracle/product/fmw/oracle_common/common/wlst/resources/wsm-wlst.jar:/u01/app/oracle/product/fmw/utils/config/10.3/config-launch.jar::/u01/app/oracle/product/fmw/wlserver_10.3/common/derby/lib/derbynet.jar:/u01/app/oracle/product/fmw/wlserver_10.3/common/derby/lib/derbyclient.jar:/u01/app/oracle/product/fmw/wlserver_10.3/common/derby/lib/derbytools.jar::

Initializing WebLogic Scripting Tool (WLST) ...

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

Connecting to WebLogic t3://stx02vsoa11.dhsie.hawaii.gov:7001 as user jyothi
Connecting to t3://stx02vsoa11.dhsie.hawaii.gov:7001 with userid xxxxx ...
Successfully connected to Admin Server 'AdminServer' that belongs to domain 'soaprd01_domain'.

Warning: An insecure protocol was used to connect to the
server. To ensure on-the-wire security, the SSL port or
Admin port should be used instead.

runScriptFromDaemon("/tmp/ot-20151020T224750811/soaDeploy.py")
Xldeploy testing
Disconnected from weblogic server: AdminServer
Processing [EligibilityDeterminationService]
Traceback (most recent call last):
File "/tmp/ot-20151020T224751659/daemon.py", line 350, in ?
exec command
File "&lt;string&gt;", line 1, in ?
File "/tmp/ot-20151020T224751659/daemon.py", line 277, in runScriptFromDaemon
execfile(scriptPath)
File "/tmp/ot-20151020T224750811/soaDeploy.py", line 495, in ?
managedServerUrl="t3://"+deployed.container.domain.servers[0].host.address+":"+str(deployed.container.domain.servers[0].port)
AttributeError: 'NoneType' object has no attribute 'address'

)</textformat>
</flashrichtext>

Thank you
Sikender

**Comment by drobichau** [comment]
Judging from the error - you are deploying to a wls.Cluster.  Make sure that server(s) (wls.Server) in the cluster have the host set.  The error indicates it is unable to pick up the address which it is getting from the host. 

If you continue to have problems can you attach screen shots of the host, server and cluster configurations.

**Comment by sikendermd** [comment]
Hi drobichau,
Yes the wls server (Admin server) is defined with host. Can you please check the configuration for me once fro the snapshots i have attached for you.
STX02VSOA11 ( Infrasturcture/SOA/STX02VSOA11) Overthere.SshHost
SOA-Domain (Infrasturcture/SOA/SOA_Domain) wls.Domain


I am also sending you the snapshot of wls server where the host(stx02vsoa11) is defined..,

Please go through it!! 


![wls server](https://cloud.githubusercontent.com/assets/15146403/10802269/2faf1060-7d79-11e5-9fc7-9c23146a3adc.png)
![host](https://cloud.githubusercontent.com/assets/15146403/10802335/959d0ce2-7d79-11e5-86df-5d4e2f18c702.png)
![cluster](https://cloud.githubusercontent.com/assets/15146403/10802341/9c80a12c-7d79-11e5-90da-0208675efa79.png)


Thank you 
Sikender

**Comment by sikendermd** [comment]
Hi drobichau,

I made some changes and tried the deployment. I found the below error: 

<flashrichtext version="1">
  <textformat font="MuseoSans" size="12" color="0" bold="false" italic="false" underline="false" url="" target="" align="left" leftMargin="0" rightMargin="0" indent="0" leading="2" blockIndent="0" kerning="false" letterSpacing="0" display="block">(Initializing WebLogic Scripting Tool (WLST) ...

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

Connecting to WebLogic t3://STX02VSOA11:7001 as user *****
Connecting to t3://STX02VSOA11:7001 with userid ***** ...
Successfully connected to Admin Server 'AdminServer' that belongs to domain 'soaprd01_domain'.

Warning: An insecure protocol was used to connect to the
server. To ensure on-the-wire security, the SSL port or
Admin port should be used instead.

runScriptFromDaemon("/tmp/ot-20151102T231138193/soaDeploy.py")
Xldeploy testing
Disconnected from weblogic server: AdminServer
Processing [EligibilityDeterminationService]
Connecting to t3://STX02VSOA11:8001 with userid ***** ...
Successfully connected to managed Server 'soa_server_01' that belongs to domain 'soaprd01_domain'.

Warning: An insecure protocol was used to connect to the
server. To ensure on-the-wire security, the SSL port or
Admin port should be used instead.
Disconnected from weblogic server: soa_server_01
result

error
DEPLOYIT-DAEMON-EXIT-VALUE: -1
Connecting to t3://STX02VSOA11:7001 with userid ***** ...
Successfully connected to Admin Server 'AdminServer' that belongs to domain 'soaprd01_domain'.

Warning: An insecure protocol was used to connect to the
server. To ensure on-the-wire security, the SSL port or
Admin port should be used instead.

Traceback (most recent call last):
File "/tmp/ot-20151102T231138965/daemon.py", line 350, in ?
exec command
File "&lt;string&gt;", line 1, in ?
File "/tmp/ot-20151102T231138965/daemon.py", line 277, in runScriptFromDaemon
execfile(scriptPath)
File "/tmp/ot-20151102T231138193/soaDeploy.py", line 555, in ?
raise Exception('Deployment failed')
java.lang.Exception: java.lang.Exception: Deployment failed
No stack trace available.
Problem invoking WLST - Traceback (innermost last):
File "/tmp/ot-20151102T231138965/daemon.py", line 357, in ?
File "/tmp/ot-20151102T231138965/daemon.py", line 280, in disconnectFromDaemonForError
File "&lt;iostream&gt;", line 428, in undo
File "&lt;iostream&gt;", line 1847, in raiseWLSTException
WLSTException: Error occured while performing undo : Cannot call Edit functions when you are not in the Edit tree.
)</textformat>
</flashrichtext>





Can you please go ahead and look into error and let me know where are we going wrong. 



Thank you 
Sikender

**Comment by jdewinne** [comment]
Hi Sikender,

I think we can close this as we got it resolved by using a folder artifact.

Regards,
Joris

**Comment by sikendermd** [comment]
Hi all,


Yes please. :-)


Thank you
Sikender
