### ISSUE TITLE
Hanging deployment when wls.Server has no Host property defined

### ISSUE THREAD

**Issue by wv0** [xebialabs-community/xld-oracle-soa-plugin#6]
SOA deployment prints error message: 
managedServerUrl="t3://"+deployed.container.servers[0].host.address+":"+str(deployed.container.servers[0].port) 
AttributeError: 'NoneType' object has no attribute 'address'

Not only is this message displayed, but XL Deploy fails to detect this as error situation; the task remains in Running state and cannot be aborted. Restart of XL Deploy server is required. The WLST process on the target environment remains running and consumes CPU.

This happens when the first host under the cluster does not have a filled-in Host. "First" is done via auto-sorting the wls.Servers under the Cluster, and actually srv2 is sorted before srv1.

This mechanism is not very transparant. Maybe it would be better if on the wls.Domain level you can also enter a hostname to use for SOA deployment. There is already a SoaPort property on wls.Domain. (But note that this should not be a "required" property in the type, because it only applies to SOA domains, not to other WLS domains. So the check should be done when a SoaComposite or Mds is attempted on this target.)

**Comment by jdewinne** [comment]
I've added a step(s) to the pre-plan that checks if the hosts have been defined on wls.Server and/or the servers part of the wls.Cluster. See release 1.3.3.
