### ISSUE TITLE
Prepare step fails while checking if container has a host set

### ISSUE THREAD

**Issue by wv0** [xebialabs-community/xld-oracle-soa-plugin#7]
The new step "Check if container ... has a host set" fails with:

    Error while executing script [scripts/checkHostProperty.py]: TypeError: 'Set' object is unsubscriptable in <script> at line number 24
    com.xebialabs.platform.script.jython.JythonException: Error while executing script [scripts/checkHostProperty.py]: TypeError: 'Set' object is unsubscriptable in <script> at line number 24

**Comment by jdewinne** [comment]
Hi,

I've got this fixed in version 1.3.4.

Regards,
Joris
