### ISSUE TITLE
No placeholder scanning in MDS artifacts

### ISSUE THREAD

**Issue by wv0** [xebialabs-community/xld-oracle-soa-plugin#8]
No placeholder scanning is performed on a JAR file of deployable type soa.MdsSOADeployableSpec.

Expectation is that the placeholder mechanism can be used in any file inside the MDS JAR.

**Comment by jdewinne** [comment]
Released 1.4.0.alpha. Also refactored the type definition to make it more compliant. Use soa.MdsSpec to have placeholder scanning enabled.

**Comment by jdewinne** [comment]
I think this got resolved with the release of 1.4.0.
